TD-423: Add confirm revoke
valitydev/api-key-mgmt pull request #13
Opened 2023-03-13 00:51 UTC by ndiezel0

2023-03-14 08:44 UTC, nanodirijabl commented on README.md
> +open_api_spec_from_json = "openapi.json" |> File.read!() |> Jason.decode!() |> OpenApiSpex.OpenApi.Decode.decode()
Может стоит создать микс таску которая будет генерить/патчить `Plugger.Generated.Spec`. 

Или в ридме отдельно описать способо ручного обновления спека.

2023-03-14 08:44 UTC, nanodirijabl commented on apps/api_key_mgmt/lib/api_key_mgmt/email.ex
> +      text_body: "Thanks for joining!"
Наверное лучше заменить заглушку текстового варианта письма на что-то другое или повторить туда текст письма если он и так не содержит тегов.

2023-03-14 08:44 UTC, nanodirijabl commented on config/runtime.exs
> +
Может лучше перенести статическую часть конфигурации в "первый" `config/config.exs` или в соответствующие окружения `dev`/`test`. Тут может потеряться связь с тем что эта конфигурация завязанная на постоянную инфраструктуру в котором будет крутиться приложение.

2023-03-14 08:44 UTC, nanodirijabl commented on README.md
> +open_api_spec_from_json = "openapi.json" |> File.read!() |> Jason.decode!() |> OpenApiSpex.OpenApi.Decode.decode()
Еще может будет удобнее если `openapi.json` перенести в `priv/` или `apps/api_key_mgmt/priv/`

2023-03-14 08:44 UTC, nanodirijabl commented on apps/api_key_mgmt/test/api_key_mgmt/handler_test.exs
> +
Забытый тест?

2023-03-30 03:27 UTC, ndiezel0 commented on config/runtime.exs
> +
Я может чего-то не понимаю, но разве у не один конфиг файл используется? Или runtime везде используется?

2023-03-30 06:49 UTC, nanodirijabl commented on config/runtime.exs
> +
Грубо говоря, скрипт `config/config.exs` исполняется при сборке перед компиляцией, а `config/runtime.exs` -- после, уже при старте самого приложения.
То есть `config/runtime.exs` дергается всегда для запуска, просто там уже нельзя влиять конфигом на компиляцию кода, но зато всегда есть точка кастомизации инстанса.

2023-04-04 10:16 UTC, nanodirijabl requested changes

2023-04-04 10:16 UTC, nanodirijabl commented on apps/api_key_mgmt/test/api_key_mgmt/handler_test.exs
> +
Забыл это.

2023-04-04 10:16 UTC, nanodirijabl commented on apps/api_key_mgmt/lib/api_key_mgmt/handler.ex
> +             api_key.party_id === party_id do
Жёстко. 
```suggestion
    with {:ok, api_key} <- ApiKeyRepository.get(api_key_id),
         ^revoke_token <- api_key.revoke_token,
         ^party_id <- api_key.party_id do
```
Может во вспомогательную функцию вынести или разбить на явный матч, а в клозы-иначе поменять:
```elixir
...
else
  {:error, :not_found} -> %NotFound{}
  :forbidden -> %Forbidden{}
  _unmatched_credentials -> %NotFound{}
end
```

2023-04-11 07:13 UTC, nanodirijabl approved these changes

2023-04-12 23:51 UTC, merged